name: codebase-engine
on: 
  schedule:
    - cron: '0 10 * * *'
jobs:
  init-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - run: yarn install
      - run: bash .github/job.sh
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      RATE_LIMIT_MINUTES: ${{ secrets.RATE_LIMIT_MINUTES }}
      RATE_LIMIT_MAX_REQUEST: ${{ secrets.RATE_LIMIT_MAX_REQUEST }}
      CACHE_STORAGE_SECONDS: ${{ secrets.CACHE_STORAGE_SECONDS }}
      CODE_SRC: ${{secrets.CODE_SRC}}