name: Vercel Dev Deployment
on: 
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - run: yarn install
      - run: yarn run test
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      RATE_LIMIT_MINUTES: ${{ secrets.RATE_LIMIT_MINUTES }}
      RATE_LIMIT_MAX_REQUEST: ${{ secrets.RATE_LIMIT_MAX_REQUEST }}
      CACHE_STORAGE_SECONDS: ${{ secrets.CACHE_STORAGE_SECONDS }}
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: .